# -*- coding: utf-8 -*-
"""Dictionary Comprehension.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yT191oE7iQzeELFU_J47A5vNHMELHgvC
"""

# Dictionary Comprehension
# new_dict = {new_key: new_value for item in list}
# new_dict = {new_key: new_value for (key, value) in dict.items()}
# new_dict = {new_key: new_value for (key, value) in dict.items() if test}
import random

from traitlets.traitlets import directional_link
names = ["Alex", "Beth", "Caroline", "Dave", "Eleanor", "Freddie"]
students_score = {student:random.randint(1,100) for student in names}
passed_students = {student:score for (student, score) in students_score.items() if score >= 60}

print(students_score)
print(passed_students)

#You are going to use Dictionary Comprehension to create a dictionary called result that takes each word
#in the given sentence and calculates the number of letters in each word.
sentence = "What is the Airspeed Velocity of an Unladen Swallow?"
# Write your code below:
result = {word:len(word) for word in sentence.split()}
print(result)

# temp convert to ferh
# To convert temp_c into temp_f:
# (temp_c * 9/5) + 32 = temp_f

weather_c = {
    "Monday": 12,
    "Tuesday": 14,
    "Wednesday": 15,
    "Thursday": 14,
    "Friday": 21,
    "Saturday": 22,
    "Sunday": 24,
}
# Write your code 👇 below:
weather_f = {key:(value * 9/5) + 32 for key, value in weather_c.items()}
print(weather_f)

student_dict = {
    "student": ["Angela", "James", "Lily"],
    "score": [56, 76, 98]
}

# Looping through dictionaries
# for (key, value) in student_dict.items():
#   print(value)

import pandas
student_data_frame = pandas.DataFrame(student_dict)
# print(student_data_frame)

# Loop through data frame
# for (key, value) in student_data_frame.items():
#   print(key, value)

# Loop through rows of a data frame
for(index, row) in student_data_frame.iterrows():
  # print(index)
  # print(row)
  # print(row.student)
  # print(row.score)
  if row.student == "Angela":
    print(row.score)

